from docx import Document
import re
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL

def normalizeName(full_name: str) -> str:
    """
    Нормализация имени из Фамилии Имени Отчества в И.О. Фамилию
    :param full_name: полное ФИО
    :return: И.О. Фамилия
    """
    parts = re.split(r'\s+', full_name.strip())
    surname = ''
    initial_parts: list = []
    for part in parts:
        if re.match(r'^[А-ЯЁ]\.(?:\.[А-ЯЁ])?$', part):
            initial_parts.extend(part.split('.'))
        elif part:
            if not initial_parts and len(part) == 1:
                initial_parts.append(part)
            else:
                if not surname:
                    surname = part
                else:
                    if len(initial_parts) < 2:
                        initial_parts.append(part[0] if len(part) > 1 else part)
    initials_str = ''
    if initial_parts:
        initials_str = '.'.join([initial[0].upper() for initial in initial_parts if initial]) + '.'
    return f"{initials_str} {surname}".strip()


class RiskMapToDocxConverter:
    """
    Класс для преобразования карты рисков в docx
    """
    def __init__(self, riskMap):
        self.riskMap = riskMap
        self.document = Document()
        self._setupDocument()
        self._setDocumentMetadata()

    def _setDocumentMetadata(self) -> None:
        """
        Настройка метаданных файла docx
        """
        core_properties = self.document.core_properties
        core_properties.author = "AURA"
        core_properties.comments = "Generated by AURA"

    def _setupDocument(self) -> None:
        """
        Подготовка документа к редактированию
        """
        # Шрифт
        self.document.styles['Normal'].font.name = 'Times New Roman'
        # Ориентация листа
        section = self.document.sections[0]
        section.orientation = WD_ORIENT.LANDSCAPE
        section.page_width, section.page_height = section.page_height, section.page_width
        # Отступы
        section.left_margin = Inches(0.5)
        section.right_margin = Inches(0.5)
        section.top_margin = Inches(0.5)
        section.bottom_margin = Inches(0.5)

    def convertToDocx(self, output_path):
        # Прербразование в docx
        self._addApprovalSection()
        self._addTitle()
        self._addMainInfo()
        self._addSummaryTable()
        self._addRiskTable()
        self._addMethods()

        self.document.save(output_path)

    def _addApprovalSection(self) -> None:
        """
        Заполнение раздела утверждения

        "Утверждаю председатель комиссии И.О. Фамилия"
        """
        # Раздел утверждения
        table = self.document.add_table(rows=3, cols=1)
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        table.autofit = False
        table.columns[0].width = Inches(3.5)

        cell = table.rows[0].cells[0]
        cell.text = "Утверждаю"
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT

        cell = table.rows[1].cells[0]
        cell.text = "Председатель комиссии"
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT

        cell = table.rows[2].cells[0]
        p = cell.paragraphs[0]
        p.add_run("______________________________________").font.size = Pt(10)

        chairman = self.riskMap.chairman
        if chairman:
                chairman = normalizeName(chairman)
        else:
            chairman = " ".join("И.О. Фамилия")
        p.add_run(chairman).font.size = Pt(10)
        p.add_run("\n______________________________20____г.").font.size = Pt(10)
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT

    def _addTitle(self) -> None:
        """
        Добавление заголовка карты риска

        "Карта № N оценки риска"
        """
        title_table = self.document.add_table(rows=1, cols=1)
        title_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        title_table.autofit = False

        cell = title_table.rows[0].cells[0]
        p = cell.paragraphs[0]
        p.add_run(f"Карта №{self.riskMap.mapNo if self.riskMap.mapNo else '___'}\n").font.bold = True
        p.add_run("оценки риска")
        p.runs[0].font.bold = True
        p.runs[1].font.bold = True
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        self.document.add_paragraph()

    def _addMainInfo(self) -> None:
        p1 = self.document.add_paragraph()
        p1.add_run("1. Название профессии\n")
        p1.add_run(self.riskMap.profession if self.riskMap.profession else "")
        p1.runs[0].font.bold = True

        p2 = self.document.add_paragraph()
        p2.add_run(f"2. Наименование структурного подразделения\n")
        p2.add_run(self.riskMap.structDivision if self.riskMap.structDivision else "")
        p2.runs[0].font.bold = True

        p3 = self.document.add_paragraph()
        p3.add_run("3. Краткое описание выполняемой работы\n")
        p3.add_run(self.riskMap.description if self.riskMap.description else "")
        p3.runs[0].font.bold = True

        p4 = self.document.add_paragraph()
        p4.add_run("4. Используемое оборудование, материалы, сырье\n")
        p4.add_run(self.riskMap.toolsMaterials if self.riskMap.toolsMaterials else "")
        p4.runs[0].font.bold = True

        p5 = self.document.add_paragraph()
        p5.add_run("5. Нормативные документы:\n")
        for doc in self.riskMap._regulatoryDocs:
            p5.add_run(f"{doc}\n")
        p5.runs[0].font.bold = True

    def _addSummaryTable(self) -> None:
        p6 = self.document.add_paragraph()
        p6.add_run("6. Сводные данные:")
        p6.runs[0].font.bold = True
        table = self.document.add_table(rows=4, cols=2)
        table.columns[0].width = Inches(4.5)
        table.columns[1].width = Inches(1.5)
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        table.autofit = False
        table.style = 'Table Grid'

        data = [
            ("Уровень профессионального риска на рабочем месте по результатам оценки:",
             str(round(self.riskMap.profRisk, 2)) if self.riskMap.profRisk else ''),
            ("Показатель, учитывающий результаты специальной оценки условий труда:",
             str(self.riskMap.kFactor) if self.riskMap.kFactor is not None else ''),
            ("Итоговый уровень профессионального риска по результатам оценки:",
             str(round(self.riskMap.result, 2)) if self.riskMap.result else ''),
            ("По степени риска рабочее место отнесено к категории:",
             self.riskMap.resultStr if self.riskMap.resultStr else '')
        ]

        for i, row in enumerate(table.rows):
            cell_desc = row.cells[0]
            cell_desc.text = data[i][0]
            cell_desc.paragraphs[0].runs[0].font.size = Pt(10)
            cell_desc.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

            cell_val = row.cells[1]
            cell_val.text = data[i][1]
            cell_val.paragraphs[0].runs[0].font.size = Pt(10)
            cell_val.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
            cell_val.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

            if i == 3 and self.riskMap.resultStr:
                if self.riskMap.resultStr == "Высокий":
                    cell_val.paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 0, 0)
                elif self.riskMap.resultStr == "Средний":
                    cell_val.paragraphs[0].runs[0].font.color.rgb = RGBColor(252, 186, 3)
                else:
                    cell_val.paragraphs[0].runs[0].font.color.rgb = RGBColor(0, 128, 0)
        self.document.add_paragraph()

    def _addRiskTable(self) -> None:
        p7 = self.document.add_paragraph()
        p7.add_run("7. Расчет уровней профессиональных рисков:")
        p7.runs[0].font.bold = True
        headers = [
            '№ п/п',
            'Номер опасности по перечню',
            'Опасность',
            'Опасное событие',
            'Качественное значение тяжести ущерба',
            'Баллы по тяжести ущерба',
            'Качественное значение подверженности опасности',
            'Баллы подверженности опасности',
            'Качественное значение вероятности возникновения опасности',
            'Вероятность возникновения опасности',
            'Сумма весовых коэффициентов',
            'Весовой коэффициент вероятности возникновения опасности',
            'Риски по идентифицированным опасностям',
            'Оценка значимости риска по отдельной опасности'
        ]
        table = self.document.add_table(rows=1, cols=len(headers))
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.style = 'Table Grid'

        col_widths = [0.4, 0.6, 2.2, 2.2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
        for i, width in enumerate(col_widths):
            table.columns[i].width = Inches(width)

        hdr_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            hdr_cells[i].text = header
            hdr_cells[i].paragraphs[0].runs[0].font.bold = True
            hdr_cells[i].paragraphs[0].runs[0].font.size = Pt(8)
            hdr_cells[i].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
            hdr_cells[i].vertical_alignment = WD_ALIGN_VERTICAL.CENTER

        weight_sum = sum(record.probabilityPts for record in self.riskMap.table) if self.riskMap.table else 0

        for i, record in enumerate(self.riskMap.table):
            row_cells = table.add_row().cells

            row_cells[0].text = str(i + 1)
            row_cells[0].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[1].text = str(record.n) if record.n else ''
            row_cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[2].text = record.danger if record.danger else ''

            row_cells[3].text = record.event if record.event else ''

            row_cells[4].text = record.damage if record.damage else ''
            row_cells[4].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[5].text = str(record.damagePts) if record.damagePts else ''
            row_cells[5].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[6].text = record.susceptibility if record.susceptibility else ''
            row_cells[6].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[7].text = str(record.susceptibilityPts) if record.susceptibilityPts else ''
            row_cells[7].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[8].text = record.probability if record.probability else ''
            row_cells[8].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[9].text = str(record.probabilityPts) if record.probabilityPts else ''
            row_cells[9].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[10].text = str(weight_sum) if i == 0 else ''
            row_cells[10].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            if record.probabilityPts and weight_sum:
                k = round(record.probabilityPts / weight_sum, 2)
                row_cells[11].text = str(k)
            else:
                row_cells[11].text = ''
            row_cells[11].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[12].text = str(record.identifiedDangersRisks) if record.identifiedDangersRisks else ''
            row_cells[12].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            row_cells[13].text = record.rating if record.rating else ''
            row_cells[13].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            for cell in row_cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.font.size = Pt(8)

        self.document.add_paragraph()

    def _addMethods(self) -> None:
        p8 = self.document.add_paragraph()
        p8.add_run("Общие меры по управлению рисками:\n")

        if not self.riskMap.methods:
            p8.add_run("")
            return

        for method in self.riskMap.methods:
            p8.add_run(f"–  {method}\n")
        p8.runs[0].font.bold = True
